MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'pre_weight/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  NO_MARGIN: True
  DEVICE_ID: ('1')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  SIE_CAMERA: False
  SIE_COE: 3.0
  JPM: False
  PAT: True
  RE_ARRANGE: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ['msmt17']
  NAMES_TARGET: ['market1501','cuhk03']
  ROOT_DIR: ('/home/l/data/lyx/data')  # H:/data '/home/l/data/lyx/data'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  FIN_MAX_EPOCHS: 80
  BASE_LR: 0.00035
  tuning_LR: 0.0000095   # 0.0000095  excellent
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 50
  EVAL_PERIOD: 20  # 120
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '/home/l/data/lyx/two_programme/CLIP-PGFD/result/baseline-0226/ViT-B-16_120.pth'

  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'Comparative_experiment/MS(all)-C3+M'
